### ISSUE TITLE
Does not load in current version of Flow

### ISSUE THREAD

**Issue by jeremymeyers** [jjw24/Wox.Plugin.Todoist#2]
Getting this error. The only think i can think of is that i had Wox installed when i installed Flow? I have since uninstalled it.\

![Screenshot 2021-03-05 12 54 03](https://user-images.githubusercontent.com/3514095/110154390-331b2600-7db2-11eb-92b6-da9fa80e92eb.png)

**Comment by jeremymeyers** [comment]
2021-03-06 00:07:45.5196|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-03-06 00:07:45.5248|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-03-06 00:07:45.5248|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-03-06 00:07:48.8974|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-03-06 00:07:48.8974|ERROR||
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: Microsoft.Windows.SecHealthUI_cw5n1h2txyewy!SecHealthUI can't find logo uri for Assets\Square44x44Logo.png in package location: C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-03-06 00:07:48.8974|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-03-06 00:07:49.7485|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-03-06 00:07:49.7485|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: UWP
Calling method: ResourceFromPri
Program path: C:\Program Files\WindowsApps\6958MaxN.Newsflow_2.1.12.1000_x64__5jrsa023thkzc
InnerException number: 1
Exception message: Unspecified error

'Newsflow opml file assotiation' violates pattern constraint of '\bms-resource:.{1,256}'.

Exception error type: HResult -2147024774
Exception thrown in called method: Not available
Possible interpretation of the error: Load pri failed @{6958MaxN.Newsflow_2.1.12.1000_x64__5jrsa023thkzc? ms-resource://6958MaxN.Newsflow/Resources/AppDescription} with HResult 2147942522 and location C:\Program Files\WindowsApps\6958MaxN.Newsflow_2.1.12.1000_x64__5jrsa023thkzc
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-03-06 00:07:49.7485|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-03-06 00:07:56.4028|INFO|App.OnStartup|Begin Flow Launcher startup ----------------------------------------------------
2021-03-06 00:07:56.4573|INFO|App.OnStartup|Runtime info:
Flow Launcher version: 1.7.2
OS Version: Microsoft Windows NT 10.0.19041.0
IntPtr Length: 8
x64: True
2021-03-06 00:07:56.6578|INFO|ImageLoader.Initialize|Preload images cost <22ms>
2021-03-06 00:07:56.6578|INFO|ImageLoader.Initialize|Number of preload images is <2>, Images Number: 2, Unique Items 2
2021-03-06 00:07:57.6038|ERROR|PluginsLoader.DotNetPlugins|-------------------------- Begin exception --------------------------
2021-03-06 00:07:57.6038|ERROR|PluginsLoader.DotNetPlugins|Can't find the required IPlugin interface for the plugin: <Todoist>
2021-03-06 00:07:57.6038|ERROR|PluginsLoader.DotNetPlugins|Exception full name:
 <System.InvalidOperationException>
2021-03-06 00:07:57.6038|ERROR|PluginsLoader.DotNetPlugins|Exception message:
 <Sequence contains no matching element>
2021-03-06 00:07:57.6275|ERROR|PluginsLoader.DotNetPlugins|Exception stack trace:
 <   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Flow.Launcher.Core.Plugin.PluginAssemblyLoader.FromAssemblyGetTypeOfInterface(Assembly assembly, Type[] types) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginAssemblyLoader.cs:line 49
   at Flow.Launcher.Core.Plugin.PluginsLoader.<>c__DisplayClass4_1.<DotNetPlugins>b__1() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 57>
2021-03-06 00:07:57.6275|ERROR|PluginsLoader.DotNetPlugins|Exception source:
 <System.Linq>
2021-03-06 00:07:57.6275|ERROR|PluginsLoader.DotNetPlugins|Exception target site:
 <Void ThrowNoMatchException()>
2021-03-06 00:07:57.6275|ERROR|PluginsLoader.DotNetPlugins|Exception HResult:
 <-2146233079>
2021-03-06 00:07:57.6275|ERROR|PluginsLoader.DotNetPlugins|-------------------------- End exception --------------------------
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|-------------------------- Begin exception --------------------------
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Can't find the required IPlugin interface for the plugin: <Wox.SpotifyPremium>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Exception full name:
 <System.InvalidOperationException>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Exception message:
 <Sequence contains no matching element>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Exception stack trace:
 <   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Flow.Launcher.Core.Plugin.PluginAssemblyLoader.FromAssemblyGetTypeOfInterface(Assembly assembly, Type[] types) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginAssemblyLoader.cs:line 49
   at Flow.Launcher.Core.Plugin.PluginsLoader.<>c__DisplayClass4_1.<DotNetPlugins>b__1() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 57>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Exception source:
 <System.Linq>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Exception target site:
 <Void ThrowNoMatchException()>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|Exception HResult:
 <-2146233079>
2021-03-06 00:07:57.6414|ERROR|PluginsLoader.DotNetPlugins|-------------------------- End exception --------------------------
2021-03-06 00:07:58.0370|INFO|PluginManager.InitializePlugins|Total init cost for <Plugin Indicator> is <23ms>
2021-03-06 00:07:58.0370|INFO|PluginManager.InitializePlugins|Total init cost for <Process Killer> is <27ms>
2021-03-06 00:07:58.0370|INFO|PluginManager.InitializePlugins|Total init cost for <Browser Bookmarks> is <227ms>
2021-03-06 00:07:58.0370|INFO|PluginManager.InitializePlugins|Total init cost for <System Commands> is <28ms>
2021-03-06 00:07:58.0370|INFO|PluginManager.InitializePlugins|Total init cost for <Shell> is <53ms>
2021-03-06 00:07:58.0370|INFO|PluginManager.InitializePlugins|Total init cost for <URL> is <28ms>
2021-03-06 00:07:58.0409|INFO|PluginManager.InitializePlugins|Total init cost for <Wox.SpotifyPremium> is <34ms>
2021-03-06 00:07:58.0409|INFO|PluginManager.InitializePlugins|Total init cost for <Calculator> is <73ms>
2021-03-06 00:07:58.0409|INFO|PluginManager.InitializePlugins|Total init cost for <Explorer> is <39ms>
2021-03-06 00:07:58.0409|INFO|PluginManager.InitializePlugins|Total init cost for <Web Searches> is <49ms>
2021-03-06 00:07:58.0815|INFO|PluginManager.InitializePlugins|Total init cost for <Todoist> is <70ms>
2021-03-06 00:07:58.0876|INFO|Flow.Launcher.Plugin.Program.Main|Preload programs cost <29ms>
2021-03-06 00:07:58.0876|INFO|Flow.Launcher.Plugin.Program.Main|Number of preload win32 programs <186>
2021-03-06 00:07:58.0876|INFO|Flow.Launcher.Plugin.Program.Main|Number of preload uwps <62>
2021-03-06 00:07:58.0876|INFO|PluginManager.InitializePlugins|Total init cost for <Program> is <88ms>
2021-03-06 00:07:58.0876|INFO|PluginManager.InitializePlugins|Total init cost for <Everything> is <83ms>
2021-03-06 00:07:58.1751|INFO|PluginManager.InitializePlugins|Total init cost for <Plugins Manager> is <173ms>
2021-03-06 00:07:58.2661|INFO|PluginManager.InitializePlugins|Total init cost for <Control Panel> is <255ms>
2021-03-06 00:07:58.8134|INFO|App.OnStartup|Dependencies Info:
Python Path: pythonw.exe
2021-03-06 00:07:58.8371|INFO|App.OnStartup|End Flow Launcher startup ----------------------------------------------------  
2021-03-06 00:07:58.8389|INFO|App.OnStartup|Startup cost <2782ms>

**Comment by jjw24** [comment]
I can't seem to repro this error. Did you install them using `pm install`?

**Comment by jeremymeyers** [comment]
> I can't seem to repro this error. Did you install them using `pm install`?

i did! maybe something is being weird because i had the wox versions installed already?

**Comment by jjw24** [comment]
When you say wox installed, you mean the original wox plugin? If so definitely back them up somewhere for keeping the settings and delete them. You can find the plugins in %APPDATA%\FlowLauncher\Plugins

Except for maybe Python plugins, all Wox plugins build on .net will not work unless they are migrated.

**Comment by jeremymeyers** [comment]
I mean i had Wox installed, then installed Flow, then uninstalled Wox, then installed the two plugins that arent working.  I don't think Wox uninstalls very cleanly.

**Comment by jeremymeyers** [comment]
ok i fixed it. i had to remove the plugins from both %APPDATA%\Wox\plugins and %APPDATA%\FlowLauncher\plugins (just doing 'pm uninstall [pluginname]' didn't do it) and then reinstall from Flow.

Is it possible that Flow looks in %appdata%\wox for stuff at any poiont?

**Comment by jjw24** [comment]
Nah flow and wox are independent, you can run both at the same time. The error msg literally says a wrong plugin interface is detected, so not sure how that has happened, you never copied those two plugin into flow's plugin folder?

**Comment by jeremymeyers** [comment]
nope!

**Comment by jjw24** [comment]
Hm strange. Anyway good it's working now
